manifest parser
ClimateImpactLab/downscaleCMIP6 pull request #326
Opened 2021-11-17 04:03 UTC by emileten

added a parser to automate the reading of intermediary output file paths in argo manifests. Notes : 

1. This function is to be used [here](https://github.com/ClimateImpactLab/downscaleCMIP6/blob/master/notebooks/downscaling_pipeline/global_validation_manual.ipynb). It will typically be run to build the `data_dict` object, to avoid having to manual find and write these paths. It should be run like :  

`get_output_paths(manifest: dict, regex: str)` where `regex` could be something like `'(?=.*create-coarse-reference)(?=.*move-chunks-to-space)'`. I have to write the calls to this function when I'll have identified the current, stable template names. 

2. This function assumes the argo manifest is already read in and converted to a `dict` object. We still need to find the way to obtain the argo manifest from the code.

2021-11-18 00:38 UTC, dgergel commented
@emileten this looks good, thanks! I think we'll have an updated stable template name soon, sorry for the confusion with the multiple templates. 

We can add the argo manifest read-in and conversion in a separate PR since you already have a concise PR description written up. And then add the calls to the function at the same time.

2021-11-18 00:40 UTC, dgergel requested changes
I just noticed one typo - otherwise this is good to go.

2021-11-18 00:40 UTC, dgergel commented on notebooks/downscaling_pipeline/science_validation_manual.py
> +        regular expression syntax str to filter nodes based on which templates where executed within a given node and before that given
where --> were

2021-11-18 01:35 UTC, emileten commented on notebooks/downscaling_pipeline/science_validation_manual.py
> +        regular expression syntax str to filter nodes based on which templates where executed within a given node and before that given
thanks ! fixed

2021-11-19 04:58 UTC, emileten commented
@dgergel would you mind merging this ? I think I don't have write access.

2021-11-22 17:48 UTC, merged