let the parser automatically find the historical files as well
ClimateImpactLab/downscaleCMIP6 pull request #353
Opened 2021-11-26 00:11 UTC by emileten

@dgergel I am separating PRs in small concise changes. Here is the one that automates the parsing of historical files. They were hard coded. 

For now this means the code only works with an ssp+historical workflow. If the need arises, it's easy to add in this flexibility (by splitting the `dict` in `collect_paths` and create one or the other based on a `bool` argument).

2021-11-29 02:26 UTC, emileten commented
@dgergel this is ready. All the options aren't there for precip, but it's very quick to expand once there is data to look at.

2021-11-29 23:26 UTC, dgergel requested changes
This all looks good to me - thanks @emileten! Just a couple changes. Nice work!

2021-11-30 00:06 UTC, emileten commented on notebooks/downscaling_pipeline/science_validation_manual.py
> +    non_historical_token = '(?=.*,target:ssp,)'
done 👍

2021-11-30 00:06 UTC, emileten commented on notebooks/downscaling_pipeline/science_validation_manual.py
> +                'historical': f(manifest, f'{historical_token}{var_token}{ssp_token}{gcm_token}(?=.*rechunk-biascorrected)')['path']#'az://biascorrected-stage/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1
done 👍

2021-11-30 00:07 UTC, merged