Quick and dirty separate biascorrectdownscale WorkflowTemplate for DTR
ClimateImpactLab/downscaleCMIP6 pull request #482
Opened 2021-12-27 08:21 UTC by emileten

An approach to use https://github.com/ClimateImpactLab/dodola/pull/163 (separate services and CLI options to apply a ceiling and a floor to DTR) and solve all the issues listed in the related PR, which are caused by DTR values slightly out of range. 

This introduces a separate `biascorrectdownscale` WorkflowTemplate for DTR that's a copy of the standard one with the `floor` and `ceiling` steps explicitely added to the upstream `dag`. We use this copy-and-change approach in order to minimize the consequences of numerical tweaks we might not keep in the future, on the standard template. 

@brews I think this is a relatively easy to understand change, and is in line with what you wanted to do, i.e avoiding doing a radical restructuring of the standard templates we have. 

I wanted to test this but I need https://github.com/ClimateImpactLab/dodola/pull/163 to be merged so that `dodola:dev` includes it. 

 - [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] docs reflect changes
 - [ ] passes ``flake8 downscale tests docs``
 - [ ] entry in HISTORY.rst

2021-12-27 23:27 UTC, brews commented
@emileten Looking at these, is there a reason both of the templates you added are scripts rather than container commands?

For example, your `apply-non-polar-dtr-ceiling` template would get shortened to

```yaml
    - name: apply-non-polar-dtr-ceiling
      inputs:
        parameters:
          - name: in-zarr
          - name: out-zarr
            value: "gs://scratch-170cd6ec/{{ workflow.uid }}/{{ pod.name }}/with_non_polar_dtr_ceiling.zarr"
      outputs:
        parameters:
          - name: out-zarr
            value: "{{ inputs.parameters.out-zarr }}"
      container:
        image: us-central1-docker.pkg.dev/downscalecmip6/private/dodola:dev
        command: [ dodola ]
        args:
          - "apply-non-polar-dtr-ceiling"
          - "{{ inputs.parameters.in-zarr }}"
          - "--out={{ inputs.parameters.out-zarr }}"
        resources:
          requests:
            memory: 16Gi
            cpu: "1000m"
          limits:
            memory: 18Gi
            cpu: "2000m"
      activeDeadlineSeconds: 1200
      retryStrategy:
        limit: 4
        retryPolicy: "Always"
        backoff:
          duration: 30s
          factor: 2 
```

2021-12-27 23:34 UTC, brews commented
@emileten My other comment is your interesting use of `apply-dtr-floor-pre-biascorrected`. It takes both training and simulation Zarrs as input and works on them in serial. Consider that it would likely be faster and more robust to have one template (`apply-dtr-floor`) that takes one input and one output, and then use that one template twice: once for the simulation zarr and again for training zarr.

You could use the same container command pattern I described here https://github.com/ClimateImpactLab/downscaleCMIP6/pull/482#issuecomment-1001798258.

2021-12-27 23:39 UTC, brews reviewed
Thanks for throwing this together, @emileten!

I left two general comments [here](https://github.com/ClimateImpactLab/downscaleCMIP6/pull/482#issuecomment-1001798258) and [here](https://github.com/ClimateImpactLab/downscaleCMIP6/pull/482#issuecomment-1001799528) .

I think this also needs a test run once https://github.com/ClimateImpactLab/dodola/pull/163 merges.

2021-12-28 00:07 UTC, emileten commented
Thanks @brews. Regarding the why I wrote a `script`, I think I used the DTR threshold application template (that's a `script`) that we have somewhere as a model and didn't realize I could just have a container. Both this and splitting the `floor` one into two steps are great suggestions, I am doing that right now.

2021-12-28 00:53 UTC, emileten commented
@brews I addressed your comments. I'll give it a try once https://github.com/ClimateImpactLab/dodola/pull/163 is merged !

2021-12-28 01:33 UTC, brews commented on workflows/templates/biascorrectdownscale.yaml
> +                  value: "{{ tasks.rechunk-biascorrected.outputs.parameters.out-zarr }}" # writing to input file !
I don't thiiiink this will work... I suspect it's going to need to write to a new output file.

2021-12-28 01:34 UTC, brews commented on workflows/templates/biascorrectdownscale.yaml
> +                  value: "{{ tasks.qplad.outputs.parameters.out-zarr }}" # modifies input file !
As noted above, I've got a feeling that you won't be able to read/write from the same Zarr Store without risking side-effects.

2021-12-29 01:41 UTC, emileten commented
@brews this is ready for a final review. I used as a model what you did for [precip](https://github.com/ClimateImpactLab/downscaleCMIP6/pull/485) in terms of modifying the `e2e` template and the `kustomization` template. 

Note that there are changes appearing for `biascorrectdownscale.yaml`, I can't figure out how to erase those. It's only aesthetics.

2021-12-29 01:45 UTC, emileten commented
Note this is actually using `dev` for `floor` and `ceiling` because of this pending PR in dodola : https://github.com/ClimateImpactLab/dodola/pull/165.

2021-12-29 02:00 UTC, brews requested changes
Hey @emileten. This is good work. I think this is just about ready. I *think* I caught one more pair of changes we need so that output biascorrected and downscaled output is written to the correct URLs.

2021-12-29 02:06 UTC, emileten commented on workflows/templates/biascorrectdownscale-dtr.yaml
> +                  value: "gs://scratch-170cd6ec/{{ workflow.uid }}/{{ pod.name }}/with-non-polar-dtr-ceiling.zarr"
Yes @brews totally. I realized that and then re-forgot about it. Thanks for catching this and quickly reviewing.

2021-12-29 03:17 UTC, emileten commented
@brews I fixed that. Not sure you wanted to look at this again or not -- if not I will merge right away.

2021-12-29 03:30 UTC, brews commented
@emileten , yeah, it's going to give you a big red mark unless you hit that "recycling" button and I check it again.

I got you... one sec.

2021-12-29 03:33 UTC, brews approved these changes
@emileten LGTM! Thanks for addressing that. I think this is set to merge whenever you're ready.

2021-12-29 03:40 UTC, merged